/** Dedicated AuraCall presentation. Untrusted labels enter only through textContent. */
export function renderDesktopClientPage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AuraCall Desktops</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0c111b;color:#e8edf7}*{box-sizing:border-box}body{margin:0}header{height:72px;display:flex;align-items:center;gap:20px;padding:0 24px;border-bottom:1px solid #293449}h1{font-size:20px;margin:0}header p{font-size:13px;color:#aab8cc;margin:4px 0 0}button,a{font:inherit}button{border:1px solid #34435b;border-radius:8px;padding:10px 14px;background:#192235;color:inherit;cursor:pointer}button:hover{background:#26354e}button:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid #81afff;outline-offset:3px}button:disabled{opacity:.5;cursor:default}#refresh{margin-left:auto}a{color:#a4c4ff}main{display:grid;grid-template-columns:240px minmax(0,1fr);height:calc(100dvh - 72px)}aside{padding:20px 12px;border-right:1px solid #293449;overflow:auto}aside h2{font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#aab8cc;margin:0 10px 14px}#desktops{display:grid;gap:8px}.desktop{text-align:left;display:flex;flex-direction:column;gap:5px;width:100%}.desktop[aria-current=true]{background:#243c63;border-color:#81afff}.desktop small{color:#aab8cc}section{min-width:0;display:flex;flex-direction:column}.toolbar{padding:16px 24px;display:flex;gap:16px;align-items:center;border-bottom:1px solid #293449}.toolbar h2{margin:0;font-size:17px}#mode{margin-left:auto;color:#a8c7ff;font-size:13px}select{background:#192235;color:inherit;border:1px solid #34435b;padding:7px;border-radius:6px}#stage{position:relative;flex:1;min-height:0;display:flex;align-items:center;justify-content:center;padding:16px;background:#080c13;overflow:auto}#frame{display:block;max-width:100%;max-height:100%;object-fit:contain}#frame[hidden]{display:none}#message{max-width:440px;text-align:center;color:#b6c2d4;line-height:1.6}#error{color:#ffc1b5;padding:0 24px}footer{padding:12px 24px;font-size:12px;color:#aab8cc;border-top:1px solid #293449}#root{display:block;margin:24px 10px 0}#updated{margin-left:12px}@media(max-width:640px){main{grid-template-columns:150px minmax(0,1fr)}header{padding:0 12px;gap:10px}header p{display:none}.toolbar{padding:12px;flex-wrap:wrap}#mode{margin-left:0}aside{padding:14px 8px}}
</style></head><body>
<header><div><h1>AuraCall Desktops</h1><p>Your browsers, grouped by desktop</p></div><button id="refresh" type="button">Refresh</button></header>
<main><aside aria-label="Desktop navigation"><h2>Desktops</h2><nav id="desktops" aria-label="AuraCall desktops"></nav><a id="root" hidden target="_blank" rel="noopener noreferrer">Open root desktop ↗</a></aside>
<section aria-label="Selected desktop"><div class="toolbar"><h2 id="title">Select a desktop</h2><label id="browser-label" hidden>Browser <select id="browser" aria-label="Browser on this desktop"></select></label><span id="mode">View only</span></div><p id="error" role="alert" hidden></p><div id="stage"><p id="message" role="status">Loading AuraCall desktops…</p><img id="frame" hidden alt="Live view of the selected AuraCall desktop" draggable="false"></div><footer>Viewing keeps your browsers running.<span id="updated"></span></footer></section></main>
<script>
(()=>{
const $=id=>document.getElementById(id);let catalog={desktops:[]},selected=new URLSearchParams(location.search).get('desktop'),browserId=new URLSearchParams(location.search).get('browser'),frameAbort,timer,stopped=false;
async function api(url,signal){const response=await fetch(url,{credentials:'same-origin',cache:'no-store',signal});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'Desktop service unavailable.');return data;}
function message(text){$('message').textContent=text;$('message').hidden=false;$('frame').hidden=true;$('frame').removeAttribute('src');$('updated').textContent='';}
function error(text){$('error').textContent=text;$('error').hidden=!text;}
function choose(name,id){selected=name;browserId=id||null;frameAbort?.abort();clearTimeout(timer);error('');message('Connecting to this desktop…');render();void frame();}
function render(){const nav=$('desktops');nav.replaceChildren();for(const item of catalog.desktops){const button=document.createElement('button');button.className='desktop';button.type='button';button.setAttribute('aria-current',String(item.name===selected));const label=document.createElement('span');label.textContent=item.label;const status=document.createElement('small');status.textContent=item.state==='ready'?item.browsers.length+' browser'+(item.browsers.length===1?'':'s'):item.state==='empty'?'No browsers':'Unavailable';button.append(label,status);button.onclick=()=>choose(item.name);nav.append(button);}
const root=$('root');root.hidden=!catalog.rootDesktopUrl;if(catalog.rootDesktopUrl)root.href=catalog.rootDesktopUrl;
const desktop=catalog.desktops.find(item=>item.name===selected);$('title').textContent=desktop?.label||'Select a desktop';$('browser-label').hidden=!desktop||desktop.browsers.length<2;const picker=$('browser');picker.replaceChildren();for(const item of desktop?.browsers||[]){const option=document.createElement('option');option.value=item.browserId;option.textContent=item.browserId;picker.append(option);}if(!desktop){message(catalog.desktops.length?'Choose a desktop to view.':'No AuraCall desktops are configured.');return;}if(desktop.state!=='ready'){message(desktop.state==='empty'?'No AuraCall browsers are running on this desktop.':desktop.message||'This desktop is unavailable.');return;}if(!desktop.browsers.some(item=>item.browserId===browserId))browserId=desktop.browsers[0].browserId;picker.value=browserId;const query=new URLSearchParams({desktop:selected,browser:browserId});history.replaceState(null,'','/desktops?'+query);}
async function frame(){clearTimeout(timer);const desktop=catalog.desktops.find(item=>item.name===selected);if(stopped||document.hidden||desktop?.state!=='ready'||!browserId)return;frameAbort?.abort();const controller=new AbortController();frameAbort=controller;const name=selected,id=browserId;try{const data=await api('/v1/desktops/'+encodeURIComponent(name)+'/frame?browser='+encodeURIComponent(id),controller.signal);if(controller.signal.aborted||name!==selected||id!==browserId)return;$('frame').src='data:image/png;base64,'+data.imageBase64;$('frame').hidden=false;$('message').hidden=true;error('');$('updated').textContent='Updated '+new Date().toLocaleTimeString();}catch(cause){if(controller.signal.aborted)return;message('The selected desktop is unavailable.');error(cause.message);}finally{if(!stopped&&!controller.signal.aborted)timer=setTimeout(frame,1500);}}
async function refresh(){try{const next=await api('/v1/desktops');catalog=next;selected=selected||catalog.defaultDesktop||catalog.desktops[0]?.name;render();void frame();}catch(cause){message('Unable to load AuraCall desktops.');error(cause.message);}}
$('refresh').onclick=refresh;$('browser').onchange=event=>choose(selected,event.target.value);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(timer);frameAbort?.abort();}else void refresh();});addEventListener('pagehide',()=>{stopped=true;clearTimeout(timer);frameAbort?.abort();});void refresh();
})();
</script></body></html>`;
}
