import type { WorkbenchCapability } from './types.js';

const commonPromptInput = [
  {
    name: 'prompt',
    required: true,
    description: 'User instruction submitted to the provider workbench.',
  },
];

export const STATIC_WORKBENCH_CAPABILITY_CATALOG: WorkbenchCapability[] = [
  {
    id: 'gemini.media.create_image',
    provider: 'gemini',
    providerLabels: ['Create image', 'Create Image', 'Images'],
    category: 'media',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'cli', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['image'] },
    safety: {},
    source: 'static_catalog',
  },
  {
    id: 'gemini.media.create_music',
    provider: 'gemini',
    providerLabels: ['Create music', 'Create Music', 'Music'],
    category: 'media',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'cli', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: {
      artifactTypes: ['music', 'video/mp4'],
      description: 'Gemini music can render through a video transport artifact.',
    },
    safety: { mayTakeMinutes: true },
    source: 'static_catalog',
  },
  {
    id: 'gemini.media.create_video',
    provider: 'gemini',
    providerLabels: ['Create video', 'Create Video', 'Videos'],
    category: 'media',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'cli', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['video'] },
    safety: { mayTakeMinutes: true, maySpendCredits: true },
    source: 'static_catalog',
  },
  {
    id: 'gemini.research.deep_research',
    provider: 'gemini',
    providerLabels: ['Deep research', 'Deep Research'],
    category: 'research',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['document', 'generated'] },
    safety: { mayTakeMinutes: true },
    source: 'static_catalog',
  },
  {
    id: 'gemini.canvas',
    provider: 'gemini',
    providerLabels: ['Canvas'],
    category: 'canvas',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'cli', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['canvas', 'document'] },
    safety: {},
    source: 'static_catalog',
  },
  {
    id: 'chatgpt.search.web_search',
    provider: 'chatgpt',
    providerLabels: ['Web search', 'Search the web'],
    category: 'search',
    invocationMode: 'pre_prompt_toggle',
    surfaces: ['browser_service', 'cli', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['generated'] },
    safety: { mayUseExternalAccount: false },
    source: 'static_catalog',
  },
  {
    id: 'chatgpt.canvas',
    provider: 'chatgpt',
    providerLabels: ['Canvas'],
    category: 'canvas',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'cli', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['canvas', 'document'] },
    safety: {},
    source: 'static_catalog',
  },
  {
    id: 'chatgpt.research.deep_research',
    provider: 'chatgpt',
    providerLabels: ['Deep research', 'Deep Research'],
    category: 'research',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['document', 'generated'] },
    safety: { mayTakeMinutes: true },
    source: 'static_catalog',
  },
  {
    id: 'chatgpt.apps',
    provider: 'chatgpt',
    providerLabels: ['Apps', 'Connect apps'],
    category: 'app',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'account_gated',
    stability: 'observed',
    requiredInputs: [],
    output: { artifactTypes: ['generated'] },
    safety: {
      requiresUserConsent: true,
      mayUseExternalAccount: true,
      notes: ['Do not auto-enable apps or connectors without user consent.'],
    },
    source: 'static_catalog',
  },
  {
    id: 'chatgpt.files.company_knowledge',
    provider: 'chatgpt',
    providerLabels: ['Company knowledge'],
    category: 'file',
    invocationMode: 'composer_attachment',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'account_gated',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['generated'] },
    safety: {
      mayUseExternalAccount: true,
      notes: ['Company knowledge is workspace/account dependent and should be discovered before invocation.'],
    },
    source: 'static_catalog',
  },
  {
    id: 'chatgpt.skills',
    provider: 'chatgpt',
    providerLabels: ['Skills'],
    category: 'skill',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'account_gated',
    stability: 'observed',
    requiredInputs: [],
    output: { artifactTypes: ['generated'] },
    safety: {
      requiresUserConsent: true,
      notes: ['Skills can be plan/account dependent and should be reported before invocation.'],
    },
    source: 'static_catalog',
  },
  {
    id: 'grok.media.imagine_image',
    provider: 'grok',
    providerLabels: ['Imagine', 'Grok Imagine'],
    category: 'media',
    invocationMode: 'tool_drawer_selection',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['image'] },
    safety: {
      maySpendCredits: true,
      notes: ['Grok Imagine browser availability is account-tier and rollout dependent.'],
    },
    source: 'static_catalog',
  },
  {
    id: 'grok.media.imagine_video',
    provider: 'grok',
    providerLabels: ['Imagine', 'Grok Imagine'],
    category: 'media',
    invocationMode: 'post_prompt_action',
    surfaces: ['browser_service', 'local_api', 'mcp'],
    availability: 'unknown',
    stability: 'observed',
    requiredInputs: commonPromptInput,
    output: { artifactTypes: ['video'] },
    safety: {
      maySpendCredits: true,
      mayTakeMinutes: true,
      notes: ['Grok Imagine video browser automation remains gated behind discovery and run-state evidence.'],
    },
    source: 'static_catalog',
  },
];
